### ISSUE TITLE
Softer stall parameter in LiftDrag plugin

### ISSUE THREAD

**Issue by kwikius** [srmainwaring/asv_sim#29]
The stall point of the LiftDrag plugin is very abrupt. How about adding a parameter stall_radius ( or some such). This represents the arc of a circle of radius stall_radius, tangent to the pre stall and post stall curves, where the cl or cd is picked off if alpha lies under the arc. By varying stall_radius from zero, the stall can be made harder or softer.

**Comment by srmainwaring** [comment]
@kwikius I think the model really needs a complete re-work, as we could add minor mods here and there, but really we want fully specified CL and CD curves over the full range of AoA [0, 180]. The current implementation is based off the model in Gazebo which is documented here:

- https://classic.gazebosim.org/tutorials?tut=aerodynamics

The sail plugin is modified to force some sort of symmetrical behaviour, because unlike aircraft which are not expected to operate in reverse a sail (or wing sail) may find itself with the airflow coming in at angles where drag dominates.

With some extra interest in the model now it's worth revisiting. We probably need different plugins for soft vs hard sails.

**Comment by kwikius** [comment]
To do it comprehensively  you might need  to compute ( or provide?)  a Reynolds number (RE) and provide a family of curves at  a selection of RE. This is the approach taken in, [XFLR5](https://www.xflr5.tech/xflr5.htm). XFLR5 interpolates a cl or cd curve at a particular RE from the family of curves it has.  You then need  strategy for RE outside the range of course.

**Comment by kwikius** [comment]
On thinking more about it, there are advantages to  having both options available.

The advantage in having a math based option, as well as the RE curve based option, is it is very easy simple way to change a particular  characteristic using one parameter.  The RE aerofoil based option will be much more work to modify to investigate a particular characteristic.

In the sailboat catamaran sim, the behaviour near stall is quite important, since the sail spends a lot of time stalled, unlike an aircraft wing. Anyway I implemented the stall radius parameter here ( No doubt it could be done more elegantly with better maths!) https://github.com/kwikius/asv_sim/blob/kwikius-skin_friction_and_cl_radius/asv_sim_gazebo_plugins/src/LiftDragModel.cc#L273 .  Arguably it is not technically a circular arc since the x and y units are different, but it smooths out the rate of change of lift around the stall region in a simply modifiable and repeatable way.

**Comment by kwikius** [comment]
Closing this. Happy to wait for the proper models
